apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      run: website
  template:
    metadata:
      labels:
        run: website
    spec:
      containers:
      - image: gcr.io/this-word-does-not-exist/website:v75
        imagePullPolicy: IfNotPresent
        name: website
        ports:
        - containerPort: 8080
          protocol: TCP
